server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Correlation-Id, "#{T(java.util.UUID).randomUUID().toString()}"

      # ✅ NUEVA ESTRUCTURA PARA CORS (keys actualizadas)
      server:
        webflux:
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gateway.gatewayms.filters: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO